### ISSUE TITLE
Ignoring Ruby warnings

### ISSUE THREAD

**Issue by RickCarlino** [mmims/sublime-text-2-ruby-markers#15]
It looks like Rcodetools runs in verbose mode by default, which causes warnings to get pasted into the buffer when using gems that are not safe in verbose mode.

A temporary solution I devised was to patch the Xmpfilter source code so that ` XMPFilter::INITIALIZE_OPTS[:warnings]` is `false`. Obviously, this is less than ideal, but it gets the job done.

Is there a preference that I can set to avoid this / ignore Ruby warnings by default?

**Comment by mmims** [comment]
Could you give some example code that demonstrates the issue?

**Comment by RickCarlino** [comment]
Hi @mmims,

Thanks for the work around- it's much better than the one I am using right now. Here's an example:

```
@ruby # => nil # !> instance variable @ruby not initialized
```

In my case, the offending code was inside of a gem, which was somewhat distracting.

Your fix seems to be good enough for what I am trying to fix though. Thanks for the help!

**Comment by mmims** [comment]
I will look into adding this as a configurable option.

**Comment by mmims** [comment]
@RickCarlino this can now be accomplished by setting `xmpfilter_warnings` to `false`.

**Comment by RickCarlino** [comment]
Thanks!
