### ISSUE TITLE
Unable to pass options to xmpfilter

### ISSUE THREAD

**Issue by nateberkopec** [mmims/sublime-text-2-ruby-markers#16]
```
# Subprocess error: command not found
{
  "check_for_rbenv": true,
  "rbenv_path": "/usr/local/bin/rbenv",
  "xmpfilter_bin_posix": "xmpfilter --rails"
}
```

What am I doing wrong here?

**Comment by mmims** [comment]
Unfortunately, the way python handles commands prevents adding parameters this way. I am working on adding some of the xmpfilter parameters to the settings file. In the meantime, you could make a change like the following:

ruby_markers.py (line 34)
```python
cmd.extend(self.settings.get("xmpfilter_bin_posix", ["xmpfilter"]))
```

ruby_markers.sublime-settings (Default)
```json
"xmpfilter_bin_posix": ["xmpfilter"]
```

ruby_markers.sublime-settings (User)
```json
"xmpfilter_bin_posix": ["xmpfilter", "--rails"]
```

**Comment by mmims** [comment]
I added a new option for this. Your new settings file should look like:

```json
{
    "ruby_manager": "rbenv",
    "xmpfilter_rails": true
}
```

**Comment by nateberkopec** [comment]
Thanks!
