### ISSUE TITLE
There was an OS error: No such file or directory

### ISSUE THREAD

**Issue by assembler** [mmims/sublime-text-2-ruby-markers#3]
I'm getting the: "There was an OS error: No such file or directory" error. I'm on the mac and using rbenv (ruby 1.9.3). Have installed the rcodetools-0.8.5.0.gem gem.

**Comment by Hoss3770** [comment]
Maybe you don't have a default rvm ruby version. I had the same problem.Setting a default rvm version with `rvm alias create default ruby-x.y.z` worked for me.
